# Generated by Django 6.1.1 on 2026-10-07 03:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0009_alter_order_courier_alter_order_delivered_at_and_more'),
        ('delivery', '0001_courier_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'PENDING – Хүргэлт үүссэн'), ('assigned', 'ASSIGNED – Хүргэгч оноогдсон'), ('accepted', 'ACCEPTED – Хүлээн авсан'), ('picked_up', 'PICKED_UP – Бараа авсан'), ('on_the_way', 'ON_THE_WAY – Хүргэлтэнд явж байна'), ('delivered', 'DELIVERED – Хүргэсэн'), ('failed', 'FAILED – Амжилтгүй'), ('cancelled', 'CANCELLED – Цуцлагдсан')], default='pending', max_length=12, verbose_name='Төлөв')),
                ('delivery_address', models.TextField(verbose_name='Хүргэх хаяг')),
                ('district', models.CharField(blank=True, default='', max_length=100, verbose_name='Дүүрэг')),
                ('phone', models.CharField(max_length=50, verbose_name='Утас')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Оноосон')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Хүлээн авсан')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Бараа авсан')),
                ('on_the_way_at', models.DateTimeField(blank=True, null=True, verbose_name='Хүргэлтэнд гарсан')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Хүргэсэн')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Амжилтгүй болсон')),
                ('failure_reason', models.CharField(blank=True, choices=[('customer_unavailable', 'Харилцагч байхгүй'), ('wrong_address', 'Хаяг буруу'), ('customer_refused', 'Харилцагч татгалзсан'), ('phone_unreachable', 'Утсаар холбогдохгүй'), ('other', 'Бусад')], default='', max_length=30, verbose_name='Амжилтгүй болсон шалтгаан')),
                ('note', models.TextField(blank=True, default='', verbose_name='Тайлбар')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='cart.order', verbose_name='Захиалга')),
            ],
            options={
                'verbose_name': 'Хүргэлт',
                'verbose_name_plural': 'Хүргэлтүүд',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Утас')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('current_status', models.CharField(choices=[('online', 'ONLINE'), ('offline', 'OFFLINE'), ('busy', 'BUSY')], default='offline', max_length=10, verbose_name='Төлөв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Хүргэгч',
                'verbose_name_plural': 'Хүргэгчид',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=12, verbose_name='Өмнөх төлөв')),
                ('to_status', models.CharField(max_length=12, verbose_name='Шинэ төлөв')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Огноо')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Өөрчилсөн')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='delivery.delivery', verbose_name='Хүргэлт')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='delivery.driver', verbose_name='Хүргэгч')),
            ],
            options={
                'verbose_name': 'Хүргэлтийн түүх',
                'verbose_name_plural': 'Хүргэлтийн түүх',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.driver', verbose_name='Хүргэгч'),
        ),
    ]
