# Generated by Django 6.1.1 on 2026-09-14 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
