# Generated by Django 6.1.1 on 2026-09-14 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_order'),
        ('store', '0004_product_stock'),
    ]

    operations = [
    ]
