# Merge migration: joins the two branches that had been left dangling
# (0005_employee_customer_profiles and 0006_alter_product_stock), so that
# `manage.py migrate` has a single leaf again.
# Generated by Django 6.1.1 on 2026-09-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_employee_customer_profiles'),
        ('store', '0006_alter_product_stock'),
    ]

    operations = [
    ]
