# Generated by Django 6.1.1 on 2026-09-17 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_category_is_active_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Ангилал', 'verbose_name_plural': 'Ангилал'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Хэрэглэгч', 'verbose_name_plural': 'Худалдан авагчид'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Ажилтан', 'verbose_name_plural': 'Ажилтнууд'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Бүтээгдэхүүн', 'verbose_name_plural': 'Бүтээгдэхүүн'},
        ),
    ]
