# Generated by Django 6.1.1 on 2026-09-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_category_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(default='Option', help_text="Dropdown label shown to customers, e.g. 'Flavor', 'Size', 'Color'", max_length=50)),
                ('value', models.CharField(help_text="The choice itself, e.g. 'Chocolate', 'Large', 'Red'", max_length=50, verbose_name='Нэр')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive options are hidden from the storefront.', verbose_name='Идэвхтэй эсэх')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='store.product')),
            ],
            options={
                'verbose_name': 'Product option',
                'verbose_name_plural': 'Product options',
                'ordering': ['option_type', 'id'],
            },
        ),
    ]
