# Generated by Django 6.1.1 on 2026-09-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_options_searchhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Бүтээгдэхүүн', 'verbose_name_plural': 'Бүтээгдэхүүн'},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ['-created_at']},
        ),
    ]
