# Generated by Django 6.1.1 on 2026-09-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_options_alter_searchhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Average customer rating, 0.0-5.0. Powers the 'Rating' sort on the storefront.",
                max_digits=2,
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When the product was added. Powers the 'Newest' sort and the Daily/Monthly/Yearly filter.",
                null=True,
            ),
        ),
    ]
