# Generated by Django 6.1.1 on 2026-10-05 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_existing_stock_as_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoption',
            options={'ordering': ['option_type', 'id'], 'verbose_name': 'Барааны сонголт', 'verbose_name_plural': 'Барааны сонголтууд'},
        ),
        migrations.AlterModelOptions(
            name='stockentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Агуулахын бүртгэл', 'verbose_name_plural': 'Агуулахын бүртгэлүүд'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Идэвхгүй ангилал дэлгүүрт харагдахгүй.', verbose_name='Идэвхтэй эсэх'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Хаяг'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Идэвхгүй хэрэглэгч нэвтэрч чадахгүй.', verbose_name='Идэвхтэй эсэх'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Утас'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hired_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ажилд орсон огноо'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Идэвхгүй ажилтан нэвтэрч чадахгүй.', verbose_name='Идэвхтэй эсэх'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Утас'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, default='Employee', max_length=100, verbose_name='Албан тушаал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Ангилал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Нэг ширхэгийн худалдан авсан үнэ. Нөөц нэмэхэд үнийг автоматаар бөглөнө; нөөц нэмэх бүр зарлага болж бүртгэгдэнэ.', max_digits=10, verbose_name='Өртөг (нэгжийн)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Бүтээгдэхүүн нэмэгдсэн огноо. "Шинэ" эрэмбэ болон Өдөр/Сар/Жилийн шүүлтэд ашиглагдана.', null=True, verbose_name='Үүссэн огноо'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Тайлбар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product/', verbose_name='Зураг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Идэвхгүй бүтээгдэхүүн дэлгүүрт харагдахгүй.', verbose_name='Идэвхтэй эсэх'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='Хямдралтай эсэх'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Үнэ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Дундаж үнэлгээ, 0.0-5.0. Дэлгүүрийн "Үнэлгээ" эрэмбэлэлтэд ашиглагдана.', max_digits=2, verbose_name='Үнэлгээ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Хямдралтай үнэ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Барааны үлдэгдэл (ширхэг)', verbose_name='Үлдэгдэл'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Идэвхгүй сонголт дэлгүүрт харагдахгүй.', verbose_name='Идэвхтэй эсэх'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='option_type',
            field=models.CharField(default='Option', help_text='Худалдан авагчид харагдах сонголтын нэр, жишээ нь "Амт", "Хэмжээ", "Өнгө"', max_length=50, verbose_name='Сонголтын төрөл'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='store.product', verbose_name='Бүтээгдэхүүн'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='value',
            field=models.CharField(help_text='Сонголтын утга, жишээ нь "Шоколад", "Том", "Улаан"', max_length=50, verbose_name='Сонголтын утга'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Үүссэн огноо'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Тоо ширхэг'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Худалдан авсан үнэ (нэгж)'),
        ),
    ]
