# Generated by Django 6.1.1 on 2026-10-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_productoption_options_alter_stockentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='Хямдралтай'),
        ),
    ]
