# Generated by Django 6.1.1 on 2026-10-10 08:38

import django.db.models.deletion
from django.db import migrations, models


_ALIASES = {
    'admin': 'Admin', 'админ': 'Admin',
    'operator': 'Operator', 'оператор': 'Operator',
    'хүргэгч': 'Хүргэгч', 'driver': 'Хүргэгч', 'courier': 'Хүргэгч',
}


def copy_single_position(apps, schema_editor):
    """Every employee's existing one-word position becomes their first row in
    the new table. The old `position` column is left untouched (nothing is
    deleted), so this is safe to run on production data and to reverse."""
    Employee = apps.get_model('store', 'Employee')
    EmployeePosition = apps.get_model('store', 'EmployeePosition')
    for employee in Employee.objects.all():
        text = (employee.position or '').strip()
        if not text:
            continue
        EmployeePosition.objects.get_or_create(
            employee=employee, position=_ALIASES.get(text.casefold(), text),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_heroslide_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='store.employee')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'position'), name='uniq_employee_position')],
            },
        ),
        migrations.RunPython(copy_single_position, migrations.RunPython.noop),
    ]
