"""
Django settings for bshop project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import dj_database_url
from decouple import config
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-fzo-8#)!@$5mo(5we8&%cd=apm6og3$4#dr56a!bx75$&i8ctq'
SECRET_KEY = os.getenv('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "bshop-five.vercel.app",
    ".vercel.app",
    "localhost",
    "127.0.0.1",
]
# Application definition

INSTALLED_APPS = [
    # Our own admin config (store/admin_site.py). It is plain django.contrib.admin
    # plus translated app/model names in the sidebar.
    'store.admin_site.BshopAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    "cloudinary",
    "cloudinary_storage",
    'store',
    'cart',
    'delivery',
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.gzip.GZipMiddleware',   # smaller HTML -> faster over slow links
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Switches Django's own translations (used all over the admin panel) to
    # whatever language the site_lang cookie holds. Must sit before
    # CommonMiddleware so the language is active for the whole request.
    'store.middleware.SiteLanguageMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bshop.urls'

# XFrameOptionsMiddleware (below) sends this on every response. The default,
# 'DENY', blocks the page from being put in an <iframe> at all - including by
# our own pages, which is what static/admin/js/popup-edit.js does to open
# the "edit" popup. 'SAMEORIGIN' still blocks any other site from framing
# us (the actual clickjacking protection this middleware exists for), it
# just stops blocking ourselves.
X_FRAME_OPTIONS = 'SAMEORIGIN'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
                'store.context_processors.categories',
                'store.context_processors.language',
                'store.context_processors.search_dropdown',
            ],
        },
    },
]

WSGI_APPLICATION = 'bshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True)
}

# The DATABASE_URL above points at Supabase's pooler on port 6543, i.e.
# PgBouncer in transaction-pooling mode: it can hand the underlying Postgres
# session to a different client as soon as one transaction ends. Django's
# admin opens a named ("server-side") cursor whenever it renders a choice
# field via QuerySet.iterator() (e.g. the Groups / User permissions widgets
# on the user change form) - a named cursor is tied to one specific Postgres
# backend session, so if PgBouncer swaps that session mid-request, the next
# fetch on it fails with "cursor ... does not exist". Turning server-side
# cursors off avoids this; see
# https://docs.djangoproject.com/en/stable/ref/databases/#transaction-pooling-mode
DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

# Our own Mongolian strings for admin texts Django's mn catalog lacks (see
# scripts/build_mn_overrides.py). Checked before Django's built-in catalogs.
LOCALE_PATHS = [BASE_DIR / 'locale']

USE_THOUSAND_SEPARATOR = True

FORMAT_MODULE_PATH = 'bshop.formats'

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

CLOUDINARY_STORAGE = {
"CLOUD_NAME": os.getenv("CLOUDINARY_CLOUD_NAME"),
"API_KEY": os.getenv("CLOUDINARY_API_KEY"),
"API_SECRET": os.getenv("CLOUDINARY_API_SECRET"),
}

STORAGES = {
"default": {
"BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
},
"staticfiles": {
"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
},
}


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CART_SESSION_ID = 'cart'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'   # login-ийн дараа очих хуудас
LOGOUT_REDIRECT_URL = 'home'  # logout-ийн дараа очих хуудас