# Generated by Django 6.1.1 on 2026-09-17 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_order_is_active_alter_order_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Захиалга', 'verbose_name_plural': 'Захиалга'},
        ),
    ]
