# Generated by Django 6.1.1 on 2026-09-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='options',
            field=models.CharField(blank=True, default='', help_text="Human-readable summary of the options chosen, e.g. 'Flavor: Chocolate, Size: Large'", max_length=255),
        ),
    ]
