# Generated by Django 6.1.1 on 2026-10-05 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_orderitem_options'),
        ('store', '0018_alter_productoption_options_alter_stockentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Захиалгын мөр', 'verbose_name_plural': 'Захиалгын мөрүүд'},
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='Хаяг'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Идэвхгүй захиалга архивлагдаж, хэрэглэгчид харагдахгүй.', verbose_name='Идэвхтэй эсэх'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Хүлээгдэж буй'), ('confirmed', 'Баталгаажсан'), ('delivered', 'Хүргэгдсэн'), ('cancelled', 'Цуцлагдсан')], default='pending', max_length=20, verbose_name='Төлөв'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч (акаунт)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Нэр'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='options',
            field=models.CharField(blank=True, default='', help_text='Сонгосон сонголтуудын товч тайлбар, жишээ нь "Амт: Шоколад, Хэмжээ: Том"', max_length=255, verbose_name='Сонголт'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order', verbose_name='Захиалга'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Үнэ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='Бүтээгдэхүүн'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Тоо ширхэг'),
        ),
    ]
