# Generated by Django 6.1.1 on 2026-10-07 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='f_courier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='f_delivered_at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='picked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='f_picked_at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Хүлээгдэж буй'), ('confirmed', 'Баталгаажсан'), ('delivered', 'Хүргэгдсэн'), ('cancelled', 'Цуцлагдсан')], default='pending', max_length=20, verbose_name='Төлөв'),
        ),
    ]
